export default [
  ['Tokyo', 'Japan', '1'],
  //   ['Delhi', 'India', 2],
  //   ['Shanghai', 'China', 3],
  //   ['São Paulo', 'Brazil', 4],
  //   ['Mexico City', 'Mexico', 5],
  //   ['Cairo', 'Egypt', 6],
  //   ['Mumbai', 'India', 7],
  //   ['Beijing', 'China', 8],
  //   ['Dhaka', 'Bangladesh', 9],
  //   ['Osaka', 'Japan', 10],
  //   ['New York City', 'United States', 11],
  //   ['Karachi', 'Pakistan', 12],
  //   ['Buenos Aires', 'Argentina', 13],
  //   ['Chongqing', 'China', 14],
  //   ['Istanbul', 'turky', 15],
];
